version: '2'

services: 

  www:
    build: ./services/www
    ports: 
      - "8000:8000"
  api:
    build: ./services/api
    ports:
      - "9000:9000"
    links:
      - rate
  rate:
    build: ./services/rate

